### PR TITLE
Modernize to Incremental Source Generators

### PR DESCRIPTION
**Pull request by viceroypenguin**

### CODE REVIEW

**Comment by viceroypenguin** [comment]
@kzu This PR strictly updates all generators to use incremental generator technology. Other PRs will follow.

**Comment by kzu** [comment]
To fix the dotnet-format, just run `dotnet format` on the repo root and commit the changes

**Comment by kzu** [comment]
Hey @viceroypenguin , thanks a lot for tackling this! I've been meaning to spend time on it for months now, he. So glad you could work on it!

It looks really nice and focused on just the conversion, which is very much appreciated.

**Comment by viceroypenguin** [comment]
> To fix the `dotnet-format` check, just run `dotnet format` on the repo root and commit the changes

Done

**Comment by kzu** [comment]
Ok, just rebased on main to get minor changes from there

**Comment by viceroypenguin** [comment]
You bet! Finally looking into doing ThisAssembly.EmbeddedResources, so cleaning things up first seemed to make sense.

**Comment by viceroypenguin** [comment]
@kzu - unrelated: would you be opposed to me changing the `SourceItemType` of the items for ThisAssembly.Strings? `"EmbeddedResource"` would be accurate for ThisAssembly.EmbeddedResource, while `"Strings"` or `"ResourceString"` would be more appropriate for ThisAssembly.Strings.

**Comment by kzu** [comment]
Wouldn't both generators be able to work off of the same SourceItemType of EmbeddedResource? The underlying generator would require a run-time embedded resource anyway, right? If so, I think the new generator could leverage the same item type as the Strings one?

**Comment by viceroypenguin** [comment]
Couple factors at play here:
* .Strings wants to import the text of the embedded resource so that it can do XML parsing. This means the full text of the resource is part of the incremental cache - it would be better for .Strings not to accidentally include .EmbeddedResources (knowing at some level that it won't due to the add'l metadata filter in StringsGenerator.cs)
* .EmbeddedResources probably does not want to import the resx files - generally those will get accessed via ResourceManager instead of EmbeddedResources since the .resx file itself is not important to the consumer. Though if it did, it really wouldn't be a significant effect.

**Pull request merged**
