### PR TITLE
Remove C#9 requirement/comment

### PR DESCRIPTION
**Pull request by viceroypenguin**

### CODE REVIEW

**Review by kzu — CHANGES_REQUESTED** [review]
This will still need to account for building against a language that does not support source generators, since the nuget package can be installed by any VS version.

Please consider the information on https://github.com/devlooped/ThisAssembly/issues/101 to make this work for downlevel environments.

**Comment by viceroypenguin** [comment]
Honestly, this is the only source generator I've seen that even pays attention to that. Looking at a larger list (https://github.com/amis92/csharp-source-generators), I've not found another one that provides this check. There is an inherent assumption that if you're willing to use source generators, you're probably using a recent version of VS, C#, and nuget. F# explicitly denies any support for SG; and most conversation re: VB is about moving to C# where support is better.

**Comment by kzu** [comment]
Still, the fact that the package uses "source generators" might not be entirely obvious to someone just scanning nuget.org for useful packages. They might miss it while reading samples from the readme. It's a little bit of extra work, but ensures users don't end up broken and wondering why (yeah, even if it's their fault :))

**Comment by kzu** [comment]
He, funny. Reviewing why the PR #134 is failing, I got a source generators error from Polysharp that shields from precisely the situation I was trying to prevent from this PR, he: https://github.com/Sergio0694/PolySharp/blob/main/src/PolySharp.SourceGenerators/PolySharp.targets

That's a concrete example of why shielding from user error is empowering. I knew what I had to do. Just update! (or stop using Polysharp... )

**Pull request closed without merging**
