### PR TITLE
Additional sanitizing at template rendering time

### LINKED ISSUE #155: Problems with Resources generator generated code
## Describe the Bug

- Relative path names (e.g., "./") generate dots (".") as partial class names
- Dashes in path names generate attempts at dashes in class names

## Steps to Reproduce

Embed the file name "./swagger-ui/swagger-ui.css" in a .csproj file

This is the result:

```c#
partial class ThisAssembly
{
    public static partial class Resources
    {
        public static partial class . <-- this is bad {

        public static partial class swagger - <-- so is this

        ui {
        /// <summary>
        /// => @"./swagger-ui/swagger-ui.css"
        /// </summary>
        public static partial class swagger -

        ui {
        public static byte[] GetBytes() => EmbeddedResource.GetBytes(@"./swagger-ui/swagger-ui.css");
        public static Stream GetStream() => EmbeddedResource.GetStream(@"./swagger-ui/swagger-ui.css");
    }
} } } }
```

[^1]: This is bad
[^2]: So is this

## Expected Behavior

Expect the output to look like either this:

```c#
partial class ThisAssembly
{
    public static partial class Resources
    {
        public static partial class swaggerui {
        /// <summary>
        /// => @"./swagger-ui/swagger-ui.css"
        /// </summary>
        public static partial class swaggerui {
        public static byte[] GetBytes() => EmbeddedResource.GetBytes(@"./swagger-ui/swagger-ui.css");
        public static Stream GetStream() => EmbeddedResource.GetStream(@"./swagger-ui/swagger-ui.css");
    }
} }
```
Or this:

```c#
partial class ThisAssembly
{
    public static partial class Resources
    {
        public static partial class swagger_ui {
        /// <summary>
        /// => @"./swagger-ui/swagger-ui.css"
        /// </summary>
        public static partial class swagger_ui {
        public static byte[] GetBytes() => EmbeddedResource.GetBytes(@"./swagger-ui/swagger-ui.css");
        public static Stream GetStream() => EmbeddedResource.GetStream(@"./swagger-ui/swagger-ui.css");
    }
} }
```

## Exception with Stack Trace

```text
error CS0111: Type 'ThisAssembly.Resources.themes' already defines a member called 'GetBytes' with the same parameter types 
```

Which also brings up another potential issue, which I'll raise in a separate ticket

## Version Info

1.1.1

## Additional Info

Nope!

### PR DESCRIPTION
**Pull request by kzu**
The existing santizing wasn't enough.

Fixes #155

### CODE REVIEW

**Comment by viceroypenguin** [comment]
FYI ThisAssembly.Resources already fixes handles it, via `Model.SanitizePart()`

**Comment by kzu** [comment]
It doesn't (at least fully). Which is why I'm sending this. With the file I added, I still get compilation errors. (I'm using the published 1.1.2)

**Comment by viceroypenguin** [comment]
Interesting. Wonder what's different vs the other files already added (swagger-ui.json), etc.

**Comment by kzu** [comment]
perhaps being top-level? The logic on that model sanitization should probably be unified (across the other generators too) and unit-tested...

**Comment by viceroypenguin** [comment]
Ah, just realized it- only the path parts are being sanitized, not the name itself. Works with swagger-ui.json because there's also swagger-ui.css, so swagger-ui is part of the path, not the name. 🤦🏼‍♂️

**Comment by viceroypenguin** [comment]
Just downloaded 1.1.3, and it still misses cases. `00.VersionHistory.sql` fails, when it should do `_00_VersionHistory`. I'd help out, but I have no idea how to fit `SanitizePart()` into ThisAssembly.Strings.

**Comment by kzu** [comment]
Yep, hopefully someone can end a PR if it's critical. I don't mind appending the `_` myself in those corner cases. Would be nicer if it just worked, but it's not critical for me.

As for reusing the name/identifier sanitization, it could just be a static class that all projects link/include and that's it.

**Pull request merged**
